### ISSUE TITLE
Thingiverse is incorrectly rendering our scad files

### ISSUE THREAD

**Issue by muesli** [muesli/modular-case#10]
They are probably using the latest official OpenSCAD release, which has issues with rendering out design, so the previews are kinda broken. This would probably also affect their customizer, should we decide to use it.

**Comment by Chaos99** [comment]
It's the `angle=` parameter of the `rotate_extrude()` function that's only supported from 2016 onwards.

I think I can replace this with an `intersection` and a disc slice to make it compatible.

**Comment by muesli** [comment]
Great find! Do you think you could also make the connectors as big as in the original design? I can provide exact measurements if you need them.

**Comment by muesli** [comment]
Nice, as mentioned in the other PR, I think for now it would be nice to remain compatible with the original design unless we got a good enough reason to diverge the design. If you think the smaller connectors have certain benefits, please never hesitate to speak up! :smiley:

**Comment by Chaos99** [comment]
Possibly fixed in #23. Please verify.
