### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by EricBuijs** [muesli/modular-case#2]
Hi muesli, I'm glad to help with this. Can you add me to the project?

**Comment by muesli** [comment]
Of course, will do!

Note: I'd still appreciate it if we could work on a fork & pull request basis. That way we can have a meaningful discussion & review changes before pushing them to master. Are you familiar with the process?

**Comment by EricBuijs** [comment]
@muesli Thanks for the help, much appreciated. Before I start scripting in OpenSCAD can I just take any part of the modular case on Thingiverse, print it and determine it's dimensions? I noticed recurring elements in the case that would fit nice in an OpenSCAD library.

**Comment by muesli** [comment]
Absolutely, there a bunch of recurring elements we can re-use! Of course, take your time and do a print of the originals, they print fairly easily without supports. I can also provide measurements for a bunch of the elements I already printed. Just let me know what you need!

**Comment by EricBuijs** [comment]
Ok, I will get back to you when I printed the parts.
